docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/app" .
    - docker push "$CI_REGISTRY_IMAGE/app"
  only:
    - master

update-production:
  image: curlimages/curl
  stage: deploy
  script:
    - curl -X POST $PORTAINER
  only:
    - master
