default:
  image: docker:latest
  services:
    - docker:dind

docker-build:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/app" .
    - docker push "$CI_REGISTRY_IMAGE/app"
  only:
    - main

update-production:
  image: curlimages/curl
  stage: deploy
  script:
    - curl -X POST $PORTAINER
  only:
    - main

docker-build:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/app:$CI_COMMIT_BRANCH" .
    - docker push "$CI_REGISTRY_IMAGE/app:$CI_COMMIT_BRANCH"
  except:
    - main
