services:
  tweel:
    build:
      target: base
    volumes:
      - .:/usr/src/app
    command: dev
    networks:
      - docker_default
      - default
    environment:
      - HOST=tweel.localhost
      - CLIENT_ID=
      - CLIENT_SECRET=
      - HASH=
    labels:
      - "traefik.http.routers.tweel.rule=Host(`tweel.localhost`)"
      - "traefik.http.routers.tweel.tls=true"
  db:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_DATABASE=tweel
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    labels:
      - "traefik.enable=false"

volumes:
  mongo:

networks:
  docker_default:
    external: true
    name: docker_default